"""initial_tables

Revision ID: 52fe9674dce1
Revises: 
Create Date: 2026-04-23 23:19:21.562552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52fe9674dce1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linter_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_name', 'rule_code', name='uq_linter_rules_tool_code')
    )
    op.create_index(op.f('ix_linter_rules_id'), 'linter_rules', ['id'], unique=False)
    op.create_index(op.f('ix_linter_rules_severity'), 'linter_rules', ['severity'], unique=False)
    op.create_index(op.f('ix_linter_rules_tool_name'), 'linter_rules', ['tool_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_content', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='reviewstatus'), nullable=False),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('octet_length(code_content) <= 524288', name='check_code_content_size'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index('ix_reviews_user_created', 'reviews', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('linter_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['linter_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linter_issues_id'), 'linter_issues', ['id'], unique=False)
    op.create_index(op.f('ix_linter_issues_review_id'), 'linter_issues', ['review_id'], unique=False)
    op.create_index(op.f('ix_linter_issues_rule_id'), 'linter_issues', ['rule_id'], unique=False)
    op.create_table('llm_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('suggestion_type', sa.Enum('CODE_FIX', 'BEST_PRACTICE', 'SECURITY', 'PERFORMANCE', 'DOCUMENTATION', 'NAMING', 'STYLE', name='suggestiontype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_suggestions_id'), 'llm_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_llm_suggestions_review_id'), 'llm_suggestions', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_suggestions_review_id'), table_name='llm_suggestions')
    op.drop_index(op.f('ix_llm_suggestions_id'), table_name='llm_suggestions')
    op.drop_table('llm_suggestions')
    op.drop_index(op.f('ix_linter_issues_rule_id'), table_name='linter_issues')
    op.drop_index(op.f('ix_linter_issues_review_id'), table_name='linter_issues')
    op.drop_index(op.f('ix_linter_issues_id'), table_name='linter_issues')
    op.drop_table('linter_issues')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index('ix_reviews_user_created', table_name='reviews')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_linter_rules_tool_name'), table_name='linter_rules')
    op.drop_index(op.f('ix_linter_rules_severity'), table_name='linter_rules')
    op.drop_index(op.f('ix_linter_rules_id'), table_name='linter_rules')
    op.drop_table('linter_rules')
    # ### end Alembic commands ###
